### PR TITLE
Change « segfault » to « illegal hardware instruction » for panicsort

### PR DESCRIPTION
**Pull request by Mistera91**

### CODE REVIEW

**Comment by jd-develop** [comment]
I’m gonna check if it works once built and under Windaube, and I’ll merge – this is too much fun x)

**Comment by jd-develop** [comment]
Sadly, it **doesn’t work** under Windaube, and will make `build.bat` crash.

```
nougaro> sort([2, 1], "panic")
Traceback (most recent call last):
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\shell.py", line 324, in <module>
    main()
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\shell.py", line 293, in main
    result, error, previous_metas = nougaro.run(
                                    ^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\nougaro.py", line 173, in run
    result = interpreter.visit(ast.node, context, False, main_visit=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\runtime\interpreter.py", line 123, in visit
    result = method(node, ctx, methods_instead_of_funcs=methods_instead_of_funcs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\runtime\interpreter.py", line 338, in visit_ListNode
    value = result.register(self.visit(element_node, ctx, methods_instead_of_funcs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\runtime\interpreter.py", line 125, in visit
    result = method(node, ctx, other_ctx, methods_instead_of_funcs=methods_instead_of_funcs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\runtime\interpreter.py", line 1332, in visit_CallNode
    return_value = result.register(value_to_call.execute(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\runtime\values\functions\builtin_function.py", line 112, in execute
    return_value = result.register(method(self, exec_ctx))
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jddev\Desktop\nougaro-illegal-hardware-instruction\src\runtime\values\functions\builtin_function.py", line 2056, in execute_sort
    from mmap import mmap, PAGESIZE, PROT_READ, PROT_WRITE, PROT_EXEC
ImportError: cannot import name 'PROT_READ' from 'mmap' (unknown location)
```

**Comment by Mistera91** [comment]
As expected. I can provide a fix but this will add a platform check and I know you don’t like it

**Comment by jd-develop** [comment]
> I can provide a fix but this will add a platform check and I know you don’t like it

That’s fine

**Review by jd-develop — APPROVED** [review]

**Review by jd-develop — APPROVED** [review]

**Review by jd-develop — APPROVED** [review]
I approve for now, we’ll see if we can fix the Windows thing

**Review by jd-develop — APPROVED** [review]

**Pull request merged**
